var demoData = demoData || {};

(function () {
	var date = new Date(),
		index = 0,
		now;
		
		now = date.setMinutes(0, 0, 0);
		// today
		date.setHours(0);
		// start of week
		date.setDate(date.getDate() - date.getDay());
		// start of data
		key = date.setFullYear(date.getFullYear() -1);
	
		demoData["responseTime"] = createData();
		
	function createData() {
		var data = {},
			sample = getData();
			length = sample.length;
		
		do {
			data[key] = sample[index++ % length];
			
			key = date.setHours(date.getHours() +1);
		} while(key < now);
	
		return data;
	}
	
	function getData() {
		return [{
            "avg": 6,
            "min": 3,
            "max": 24
        }, {
            "avg": 7,
            "min": 4,
            "max": 12
        }, {
            "avg": 7,
            "min": 4,
            "max": 13
        }, {
            "avg": 6,
            "min": 3,
            "max": 23
        }, {
            "avg": 7,
            "min": 3,
            "max": 12
        }, {
            "avg": 6,
            "min": 4,
            "max": 17
        }, {
            "avg": 7,
            "min": 3,
            "max": 17
        }, {
            "avg": 7,
            "min": 4,
            "max": 13
        }, {
            "avg": 6,
            "min": 4,
            "max": 12
        }, {
            "avg": 7,
            "min": 4,
            "max": 15
        }, {
            "avg": 7,
            "min": 4,
            "max": 13
        }, {
            "avg": 6,
            "min": 4,
            "max": 10
        }, {
            "avg": 7,
            "min": 4,
            "max": 12
        }, {
            "avg": 6,
            "min": 4,
            "max": 12
        }, {
            "avg": 7,
            "min": 4,
            "max": 12
        }, {
            "avg": 7,
            "min": 4,
            "max": 13
        }, {
            "avg": 6,
            "min": 4,
            "max": 14
        }, {
            "avg": 7,
            "min": 4,
            "max": 13
        }, {
            "avg": 6,
            "min": 4,
            "max": 22
        }, {
            "avg": 7,
            "min": 4,
            "max": 19
        }, {
            "avg": 6,
            "min": 4,
            "max": 15
        }, {
            "avg": 7,
            "min": 5,
            "max": 32
        }, {
            "avg": 7,
            "min": 5,
            "max": 15
        }, {
            "avg": 6,
            "min": 4,
            "max": 11
        },{
            "avg": 6,
            "min": 3,
            "max": 58
        }, {
            "avg": 7,
            "min": 3,
            "max": 176
        }, {
            "avg": 6,
            "min": 3,
            "max": 15
        }, {
            "avg": 6,
            "min": 3,
            "max": 83
        }, {
            "avg": 7,
            "min": 2,
            "max": 66
        }, {
            "avg": 5,
            "min": 3,
            "max": 32
        }, {
            "avg": 5,
            "min": 3,
            "max": 21
        }, {
            "avg": 6,
            "min": 3,
            "max": 19
        }, {
            "avg": 5,
            "min": 3,
            "max": 34
        }, {
            "avg": 6,
            "min": 3,
            "max": 37
        }, {
            "avg": 5,
            "min": 2,
            "max": 39
        }, {
            "avg": 6,
            "min": 3,
            "max": 14
        }, {
            "avg": 5,
            "min": 2,
            "max": 42
        }, {
            "avg": 6,
            "min": 3,
            "max": 18
        }, {
            "avg": 5,
            "min": 2,
            "max": 19
        }, {
            "avg": 6,
            "min": 3,
            "max": 17
        }, {
            "avg": 5,
            "min": 3,
            "max": 11
        }, {
            "avg": 9,
            "min": 2,
            "max": 176
        }, {
            "avg": 5,
            "min": 3,
            "max": 23
        }, {
            "avg": 5,
            "min": 4,
            "max": 16
        }, {
            "avg": 5,
            "min": 3,
            "max": 21
        }, {
            "avg": 6,
            "min": 3,
            "max": 15
        }, {
            "avg": 5,
            "min": 4,
            "max": 14
        }, {
            "avg": 7,
            "min": 3,
            "max": 48
        }, {
            "avg": 6,
            "min": 3,
            "max": 57
        }, {
            "avg": 7,
            "min": 4,
            "max": 23
        }, {
            "avg": 5,
            "min": 3,
            "max": 27
        }, {
            "avg": 7,
            "min": 4,
            "max": 16
        }, {
            "avg": 5,
            "min": 2,
            "max": 37
        }, {
            "avg": 6,
            "min": 3,
            "max": 17
        }, {
            "avg": 5,
            "min": 3,
            "max": 31
        }, {
            "avg": 6,
            "min": 3,
            "max": 15
        }, {
            "avg": 5,
            "min": 3,
            "max": 39
        }, {
            "avg": 8,
            "min": 3,
            "max": 96
        }, {
            "avg": 6,
            "min": 3,
            "max": 29
        }, {
            "avg": 6,
            "min": 3,
            "max": 60
        }, {
            "avg": 6,
            "min": 4,
            "max": 35
        }, {
            "avg": 6,
            "min": 3,
            "max": 65
        }, {
            "avg": 5,
            "min": 2,
            "max": 24
        }, {
            "avg": 7,
            "min": 3,
            "max": 42
        }, {
            "avg": 8,
            "min": 2,
            "max": 60
        }, {
            "avg": 7,
            "min": 4,
            "max": 146
        }, {
            "avg": 7,
            "min": 3,
            "max": 56
        }, {
            "avg": 6,
            "min": 4,
            "max": 44
        }, {
            "avg": 6,
            "min": 4,
            "max": 29
        }, {
            "avg": 8,
            "min": 4,
            "max": 144
        }, {
            "avg": 6,
            "min": 4,
            "max": 26
        }, {
            "avg": 6,
            "min": 4,
            "max": 35
        }, {
            "avg": 6,
            "min": 3,
            "max": 66
        }, {
            "avg": 7,
            "min": 3,
            "max": 53
        }, {
            "avg": 6,
            "min": 3,
            "max": 33
        }, {
            "avg": 9,
            "min": 2,
            "max": 180
        }, {
            "avg": 11,
            "min": 2,
            "max": 180
        }, {
            "avg": 6,
            "min": 3,
            "max": 19
        }, {
            "avg": 6,
            "min": 3,
            "max": 23
        }, {
            "avg": 7,
            "min": 4,
            "max": 71
        }, {
            "avg": 7,
            "min": 4,
            "max": 58
        }, {
            "avg": 8,
            "min": 3,
            "max": 81
        }, {
            "avg": 7,
            "min": 3,
            "max": 166
        }, {
            "avg": 6,
            "min": 3,
            "max": 62
        }, {
            "avg": 7,
            "min": 3,
            "max": 20
        }, {
            "avg": 6,
            "min": 3,
            "max": 29
        }, {
            "avg": 5,
            "min": 3,
            "max": 24
        }, {
            "avg": 7,
            "min": 4,
            "max": 51
        }, {
            "avg": 6,
            "min": 3,
            "max": 26
        }, {
            "avg": 8,
            "min": 4,
            "max": 101
        }, {
            "avg": 7,
            "min": 3,
            "max": 28
        }, {
            "avg": 8,
            "min": 4,
            "max": 150
        }, {
            "avg": 7,
            "min": 4,
            "max": 16
        }, {
            "avg": 6,
            "min": 4,
            "max": 23
        }, {
            "avg": 7,
            "min": 4,
            "max": 19
        }, {
            "avg": 6,
            "min": 4,
            "max": 19
        }, {
            "avg": 6,
            "min": 4,
            "max": 31
        }, {
            "avg": 7,
            "min": 4,
            "max": 14
        }, {
            "avg": 6,
            "min": 3,
            "max": 68
        }, {
            "avg": 6,
            "min": 3,
            "max": 58
        }, {
            "avg": 6,
            "min": 2,
            "max": 27
        }, {
            "avg": 6,
            "min": 4,
            "max": 17
        }, {
            "avg": 7,
            "min": 4,
            "max": 55
        }, {
            "avg": 7,
            "min": 4,
            "max": 31
        }, {
            "avg": 8,
            "min": 4,
            "max": 106
        }, {
            "avg": 6,
            "min": 3,
            "max": 32
        }, {
            "avg": 6,
            "min": 4,
            "max": 12
        }, {
            "avg": 6,
            "min": 3,
            "max": 12
        }, {
            "avg": 7,
            "min": 3,
            "max": 105
        }, {
            "avg": 6,
            "min": 3,
            "max": 34
        }, {
            "avg": 6,
            "min": 3,
            "max": 16
        }, {
            "avg": 6,
            "min": 3,
            "max": 12
        }, {
            "avg": 7,
            "min": 3,
            "max": 88
        }, {
            "avg": 8,
            "min": 4,
            "max": 115
        }, {
            "avg": 10,
            "min": 2,
            "max": 161
        }, {
            "avg": 6,
            "min": 4,
            "max": 20
        }, {
            "avg": 8,
            "min": 4,
            "max": 85
        }, {
            "avg": 7,
            "min": 4,
            "max": 17
        }, {
            "avg": 6,
            "min": 4,
            "max": 29
        }, {
            "avg": 7,
            "min": 4,
            "max": 31
        }, {
            "avg": 7,
            "min": 3,
            "max": 52
        }, {
            "avg": 6,
            "min": 4,
            "max": 26
        }, {
            "avg": 8,
            "min": 5,
            "max": 35
        }, {
            "avg": 6,
            "min": 4,
            "max": 23
        }, {
            "avg": 7,
            "min": 3,
            "max": 28
        }, {
            "avg": 6,
            "min": 3,
            "max": 18
        }, {
            "avg": 6,
            "min": 4,
            "max": 13
        }, {
            "avg": 7,
            "min": 4,
            "max": 29
        }, {
            "avg": 6,
            "min": 4,
            "max": 35
        }, {
            "avg": 7,
            "min": 4,
            "max": 35
        }, {
            "avg": 6,
            "min": 3,
            "max": 31
        }, {
            "avg": 7,
            "min": 3,
            "max": 96
        }, {
            "avg": 12,
            "min": 4,
            "max": 197
        }, {
            "avg": 10,
            "min": 3,
            "max": 115
        }, {
            "avg": 6,
            "min": 3,
            "max": 13
        }, {
            "avg": 7,
            "min": 3,
            "max": 16
        }, {
            "avg": 7,
            "min": 4,
            "max": 80
        }, {
            "avg": 8,
            "min": 4,
            "max": 60
        }, {
            "avg": 11,
            "min": 3,
            "max": 127
        }, {
            "avg": 6,
            "min": 4,
            "max": 19
        }, {
            "avg": 6,
            "min": 4,
            "max": 16
        }, {
            "avg": 7,
            "min": 4,
            "max": 42
        }, {
            "avg": 7,
            "min": 4,
            "max": 29
        }, {
            "avg": 6,
            "min": 4,
            "max": 16
        }, {
            "avg": 8,
            "min": 4,
            "max": 42
        }, {
            "avg": 6,
            "min": 4,
            "max": 15
        }, {
            "avg": 7,
            "min": 4,
            "max": 16
        }, {
            "avg": 7,
            "min": 4,
            "max": 65
        }, {
            "avg": 6,
            "min": 3,
            "max": 40
        }, {
            "avg": 7,
            "min": 4,
            "max": 16
        }, {
            "avg": 6,
            "min": 5,
            "max": 14
        }, {
            "avg": 8,
            "min": 5,
            "max": 20
        }, {
            "avg": 6,
            "min": 4,
            "max": 12
        }, {
            "avg": 7,
            "min": 4,
            "max": 12
        }, {
            "avg": 6,
            "min": 4,
            "max": 12
        }, {
            "avg": 7,
            "min": 4,
            "max": 13
        }, {
            "avg": 6,
            "min": 4,
            "max": 10
        }, {
            "avg": 7,
            "min": 4,
            "max": 13
        }, {
            "avg": 6,
            "min": 4,
            "max": 9
        }, {
            "avg": 7,
            "min": 4,
            "max": 12
        }, {
            "avg": 6,
            "min": 4,
            "max": 12
        }, {
            "avg": 6,
            "min": 4,
            "max": 19
        }, {
            "avg": 7,
            "min": 4,
            "max": 12
        }, {
            "avg": 7,
            "min": 4,
            "max": 15
        }, {
            "avg": 6,
            "min": 4,
            "max": 16
        }, {
            "avg": 7,
            "min": 4,
            "max": 13
        }, {
            "avg": 6,
            "min": 4,
            "max": 17
        }, {
            "avg": 7,
            "min": 4,
            "max": 13
        }];
	}
})();